window.onload = function(){
    var partFixe=false;
    var partVar=false;
    var pagination=false;
    // mouseover
    d3.select('#pagination').on('mouseover',function(){
                    d3.select('#pag').attr('fill','white');});
    d3.select('#pagination').on('mouseout',function(){
                    d3.select('#pag').attr('fill',"#C4C4C4");});
    d3.select('#partVar').on('mouseover',function(){
                    d3.select('#var').attr('fill','white');});
    d3.select('#partVar').on('mouseout',function(){
                    d3.select('#var').attr('fill',"#C4C4C4");});
    d3.select('#VaetVient').on('mouseover',function(){
                    d3.select('#va').attr('fill','white');});
    d3.select('#VaetVient').on('mouseout',function(){
                    d3.select('#va').attr('fill',"#C4C4C4");});
    d3.select('#buddySystem').on('mouseover',function(){
                    d3.select('#buddy').attr('fill','white');});
    d3.select('#buddySystem').on('mouseout',function(){
                    d3.select('#buddy').attr('fill',"#C4C4C4");});
    d3.select('#partFix').on('mouseover',function(){
                        d3.select('#fix').attr('fill','white');});
    d3.select('#partFix').on('mouseout',function(){
                        d3.select('#fix').attr('fill',"#C4C4C4");});
    d3.select('#gestion').on('mouseover',function(){
                        d3.select('#ges').attr('fill','white');});
    d3.select('#gestion').on('mouseout',function(){
                        d3.select('#ges').attr('fill',"#DBDCE1");});
                                        
    ///////////////////
    d3.select('#lfu').on('mouseover',function(){
             d3.select('#lfU').attr('fill','white');});
    d3.select('#lfu').on('mouseout',function(){
             d3.select('#lfU').attr('fill',"#B8B8B8");});
    d3.select('#fifo').on('mouseover',function(){
             d3.select('#fifO').attr('fill','white');});
    d3.select('#fifo').on('mouseout',function(){
              d3.select('#fifO').attr('fill',"#B8B8B8");});
    d3.select('#lru').on('mouseover',function(){
              d3.select('#lrU').attr('fill','white');});
    d3.select('#lru').on('mouseout',function(){
              d3.select('#lrU').attr('fill',"#B8B8B8");});
    d3.select('#aging').on('mouseover',function(){
              d3.select('#aginG').attr('fill','white');});
    d3.select('#aging').on('mouseout',function(){
              d3.select('#aginG').attr('fill',"#B8B8B8");});
    //////////
    d3.select('#fileSep').on('mouseover',function(){
              d3.select('#fSep').attr('fill','white');});
    d3.select('#fileSep').on('mouseout',function(){
              d3.select('#fSep').attr('fill',"#B8B8B8");});
    d3.select('#fileCom').on('mouseover',function(){
              d3.select('#fCom').attr('fill','white');});
    d3.select('#fileCom').on('mouseout',function(){
               d3.select('#fCom').attr('fill',"#B8B8B8");});
    //////////
    d3.select('#bestFit').on('mouseover',function(){
        d3.select('#bFit').attr('fill','white');});
    d3.select('#bestFit').on('mouseout',function(){
        d3.select('#bFit').attr('fill',"#B8B8B8");});
    d3.select('#worstFit').on('mouseover',function(){
        d3.select('#wFit').attr('fill','white');});
    d3.select('#worstFit').on('mouseout',function(){
         d3.select('#wFit').attr('fill',"#B8B8B8");});
    d3.select('#firstFit').on('mouseover',function(){
         d3.select('#fFit').attr('fill','white');});
    d3.select('#firstFit').on('mouseout',function(){
         d3.select('#fFit').attr('fill',"#B8B8B8");});
    d3.select('#nextFit').on('mouseover',function(){
         d3.select('#nFit').attr('fill','white');});
    d3.select('#nextFit').on('mouseout',function(){
         d3.select('#nFit').attr('fill',"#B8B8B8");});
    /////////
    d3.select("#partFix").on('click',function(){
        d3.select("#partVarHide").style("visibility","hidden");
        d3.select("#paginationHide").style("visibility","hidden");
        partVar=false;
        pagination=false;
        if(!partFixe){
            d3.select("#partFixeHide").style("visibility","visible");
            partFixe=true;
        }else{
            d3.select("#partFixeHide").style("visibility","hidden");
            partFixe=false;
        }
    });
    d3.select("#partVar").on('click',function(){
        d3.select("#partFixeHide").style("visibility","hidden");
        d3.select("#paginationHide").style("visibility","hidden");
        partFixe=false;
        pagination=false;
        if(!partVar){
            d3.select("#partVarHide").style("visibility","visible");
            partVar=true;
        }else{
            d3.select("#partVarHide").style("visibility","hidden");
            partVar=false;
        }
    });
    d3.select("#pagination").on('click',function(){
        d3.select("#partVarHide").style("visibility","hidden");
        d3.select("#partFixeHide").style("visibility","hidden");
        partVar=false;
        partFixe=false;
        
        if(!pagination){
            d3.select("#paginationHide").style("visibility","visible");
            pagination=true;
        }else{
            d3.select("#paginationHide").style("visibility","hidden");
            pagination=false;
        }
    });
    ///// accées au page ///////
    d3.select("#fifo").on('click',function()
    {
        window.location.href="../MethodesDallocations/PaginationFIFO/PaginationFifo.html";
    });
    d3.select("#lru").on('click',function()
    {
        window.location.href="../MethodesDallocations/PaginationLRU/PaginationLRU.html";
    });
    d3.select("#lfu").on('click',function()
    {
        window.location.href="../MethodesDallocations/PaginationLFU/PaginationLFU.html";
    });
    d3.select("#aging").on('click',function()
    {
        window.location.href="../MethodesDallocations/PaginationAging/PaginationAging.html";
    });
    d3.select("#firstFit").on('click',function()
    {
        window.location.href="../MethodesDallocations/partitionsVariables/PartitionVariablefirst.html";
    });
    d3.select("#nextFit").on('click',function()
    {
        window.location.href="../MethodesDallocations/partitionsVariables/PartitionVariablenext.html";
    });
    d3.select("#bestFit").on('click',function()
    {
        window.location.href="../MethodesDallocations/partitionsVariables/PartitionVariablebest.html";
    });
    d3.select("#worstFit").on('click',function()
    {
        window.location.href="../MethodesDallocations/partitionsVariables/PartitionVariableworst.html";
    });
    d3.select("#VaetVient").on('click',function(){
        window.location.href="../MethodesDallocations/swapping/VaEtVientFirst.html"
    })
    d3.select('#fileSep').on('click',function(){
        window.location.href="../MethodesDallocations/partitionsFixesFilesSeparees/FileSeparee.html"
    })
    d3.select('#buddySystem').on('click',function(){
        window.location.href="../MethodesDallocations/BuddySystem/BuddySystem.html"

    });

d3.select('#fileCom').on('click',function(){
    window.location.href="../MethodesDallocations/partitionsFixesFileCommune/FileCommuneFinale.html"})
}